---

- name: Get ec2 facts
  ec2_facts:
  tags: worker

- name: Check if "Swarm Mode" is enabled.
  shell: "docker info | egrep '^Swarm: ' | cut -d ' ' -f2"
  changed_when: False
  register: swarm_status
  tags: worker

- name: Grab token from parameter store
  set_fact:
    current_worker_token: "{{ lookup('ssm', item.key, item.region) }}"
  with_items:
    -  { key: "swarm_{{cluster_name}}_worker_token", region: "region={{ ansible_ec2_placement_region }}" }
  tags: worker

- name: Grab address from parameter store
  set_fact:
    current_manager_address: "{{ lookup('ssm', item.key, item.region) }}"
  with_items:
    - { key: "swarm_{{cluster_name}}_manager_address", region: "region={{ ansible_ec2_placement_region }}" }
  tags: worker

- name: Join if existing swarm
  command: >
    docker swarm join
    --token={{ current_worker_token }} {{ current_manager_address }}:2377
  when:
    - current_worker_token != ""
    - swarm_status.stdout == "inactive"
  register: join_swarm
  tags: worker
